- name: Install openSSH
    win_chocolatey:
      name: "{{ item.package_name` }}"
      params: "{{ item.parameters  }}"
      state: latest
    with_items: 
    - "{{ service }}"
  when: ansible_distribution == 'Microsoft Windows Server 2012 R2 Standard'
