- name: Start Windows Service 
  win_service:
   name: "{{ item }}"
   state: started 
  with_items: 
  - "{{ service_name }}"
  when: ansible_distribution == 'Microsoft Windows Server 2012 R2 Standard'
