- name: debug 
  check_mode: yes
  debug:
   var: "{{ item.First_Name }}"
  debug:
   var: "{{ item.Last_Name }}"
  with_items:
     - "{{ user_info }}"



- name: Add Users
  win_domain_user: 
    name: "{{ item.Name }}"
    firstname: "{{ item.First_Name }}"
    surname: "{{ item.Last_Name }}"
    password: "{{ item.Password }}"
    email: "{{ item.Name }}@ad1.0154.example.opentlc.com"
    state: present 
  with_items: 
  - "{{ user_info }}" 
