- name: Open windows firewall ports
  win_firewall_rule:
    name: "{{ item.service_name }}"
    localport: "{{ item.local_port }}"
    action: allow
    direction: in
    protocol: "{{ item.protocol_name }}"
    state: present
    enabled: yes 
  with_items:
  - "{{ service }}" 
  when: ansible_distribution == 'Microsoft Windows Server 2012 R2 Standard'
